Repository PDAL/PDAL, pull requests merged in 2020-07, with the labels that each got.

#3159 filters.overlay should stop checking polygons after finding one containing a point
  filters/OverlayFilter.cpp
Labels: bug, performance

#3167 Don't copy point refs.
  plugins/e57/io/E57Reader.cpp
  plugins/e57/io/Scan.cpp
  plugins/e57/io/Scan.hpp
Labels: bug

#3170 Clear PCD header before filling
  io/PcdHeader.cpp
  io/PcdHeader.hpp
  io/PcdReader.cpp
  io/PcdReader.hpp
  io/PcdWriter.cpp
  io/PcdWriter.hpp
Labels: bug

#3186 implement spell checking on the docs and fix some speling mistakes
  .github/workflows/docs.yml
  doc/Makefile
  doc/about.rst
  doc/conf.py
  doc/development/metadata.rst
  doc/development/overview.rst
  doc/project/conventions.rst
  doc/spelling_wordlist.txt
  doc/stages/filters.colorinterp.rst
  doc/stages/filters.cpd.rst
  doc/stages/filters.dem.rst
  doc/stages/filters.hag.rst
  doc/stages/filters.hag_delaunay.rst
  doc/stages/filters.iqr.rst
  doc/stages/filters.litree.rst
  doc/stages/filters.mad.rst
  doc/stages/filters.outlier.rst
  doc/stages/filters.overlay.rst
  doc/stages/filters.pmf.rst
  doc/stages/filters.poisson.rst
  doc/stages/filters.projpipeline.rst
  doc/stages/filters.reciprocity.rst
  doc/stages/filters.reprojection.rst
  doc/stages/filters.splitter.rst
  doc/stages/filters.transformation.rst
  doc/stages/readers.geowave.rst
  doc/stages/readers.i3s.rst
  doc/stages/readers.las.rst
  doc/stages/readers.sbet.rst
  doc/stages/readers.slpk.rst
  doc/stages/readers.terrasolid.rst
  doc/tutorial/clipping/index.rst
  doc/tutorial/ground-filters.rst
  doc/tutorial/las.rst
  doc/workshop/exercises/analysis/ground/ground.rst
  doc/workshop/exercises/analysis/meshing/meshing.rst
  doc/workshop/exercises/analysis/rasterize/rasterize.rst
  doc/workshop/exercises/batch_processing/batch-processing.rst
  doc/workshop/exercises/translation/entwine.rst
  doc/workshop/lidar-introduction.rst
  pdal/util/Bounds.hpp
  pdal/util/Utils.hpp
  scripts/ci/build_docs.sh
Labels: documentation

#3193 Prevent macro expansion of isspecial() on FreeBSD. Fixes: #3190
  io/TextReader.cpp
Labels: bug

#3184 Make readers.head streamable
  filters/HeadFilter.cpp
  filters/HeadFilter.hpp
  plugins/rdb/CMakeLists.txt
  scripts/conda/osx.sh
Labels: bug

#3180 Add OptimalNeighborhoodFilter and refactor CovarianceFeaturesFilter
  doc/stages/filters.covariancefeatures.rst
  doc/stages/filters.optimalneighborhood.rst
  doc/stages/filters.rst
  filters/CovarianceFeaturesFilter.cpp
  filters/CovarianceFeaturesFilter.hpp
  filters/OptimalNeighborhoodFilter.cpp
  filters/OptimalNeighborhoodFilter.hpp
  pdal/Dimension.json
  test/unit/filters/CovarianceFeaturesTest.cpp
Labels: feature, stage
