Repository PDAL/PDAL, pull requests merged in 2020-11, with the labels that each got.

#3294 Misc. Changes To Fix CI and Memory Leaks
  .github/workflows/linux.yml
  io/ObjReader.cpp
  io/ObjReader.hpp
  pdal/util/CMakeLists.txt
  plugins/tiledb/CMakeLists.txt
  plugins/tiledb/io/TileDBReader.cpp
  plugins/tiledb/test/TileDBWriterTest.cpp
  test/unit/io/LasWriterTest.cpp
Labels: bug

#3295 Fix JSON format for ogr writer example in docs
  doc/stages/writers.ogr.rst
Labels: bug, documentation

#3265 Initial commit of TEASER++
  cmake/options.cmake
  doc/references.rst
  doc/stages/filters.teaser.rst
  plugins/CMakeLists.txt
  plugins/teaser/CMakeLists.txt
  plugins/teaser/filters/TeaserFilter.cpp
  plugins/teaser/filters/TeaserFilter.hpp
  plugins/teaser/filters/registration.h
  plugins/teaser/test/TeaserFilterTest.cpp
Labels: feature

#3183 Add chamfer distance to PDALUtils and expose via kernel
  doc/apps/chamfer.rst
  kernels/ChamferKernel.cpp
  kernels/ChamferKernel.hpp
  pdal/PDALUtils.cpp
  pdal/PDALUtils.hpp
  test/unit/CMakeLists.txt
  test/unit/apps/ChamferTest.cpp
Labels: feature, stage

#3300 Don't use conda compiler
  scripts/ci/linux/setup.sh
Labels: bug
