Repository PDAL/PDAL, pull requests merged in 2020-02, with the labels that each got.

#2895 move Python to https://github.com/PDAL/python
  plugins/CMakeLists.txt
  plugins/matlab/filters/Environment.cpp
  plugins/python/CMakeLists.txt
  plugins/python/filters/CMakeLists.txt
  plugins/python/filters/PythonFilter.cpp
  plugins/python/filters/PythonFilter.hpp
  plugins/python/io/CMakeLists.txt
  plugins/python/io/NumpyReader.cpp
  plugins/python/io/NumpyReader.hpp
  plugins/python/plang/Environment.cpp
  plugins/python/plang/Environment.hpp
  plugins/python/plang/Invocation.cpp
  plugins/python/plang/Invocation.hpp
  plugins/python/plang/Redirector.cpp
  plugins/python/plang/Redirector.hpp
  plugins/python/plang/Script.cpp
  plugins/python/plang/Script.hpp
  plugins/python/test/NumpyReaderTest.cpp
  plugins/python/test/PythonFilterTest.cpp
  plugins/python/test/make-test-data.py
  scripts/azp/linux.yml
  scripts/azp/osx.yml
  scripts/azp/win.yml
  scripts/ci/script.sh
  scripts/conda/osx.sh
Labels: policy-decision

#2911 Implement a Linux build based on Conda with a pinned GDAL dependency
  azure-pipelines.yml
  plugins/tiledb/CMakeLists.txt
  scripts/azp/linux-conda.yml
Labels: build

#2900 Add reader, now, and file_size keys to pdal info output
  kernels/InfoKernel.cpp
  scripts/docker/ubuntu/Dockerfile
  test/unit/apps/InfoTest.cpp
Labels: feature

#2915 Refined wording of transformation filter documentation
  doc/images/filters.transformation.rotation_x_axis_counter-clockwise.svg
  doc/images/filters.transformation.rotation_x_axis_counter-clockwise.svg.png
  doc/images/filters.transformation.rotation_y_axis_counter-clockwise.svg
  doc/images/filters.transformation.rotation_y_axis_counter-clockwise.svg.png
  doc/images/filters.transformation.rotation_z_axis_counter-clockwise.svg
  doc/images/filters.transformation.rotation_z_axis_counter-clockwise.svg.png
  doc/images/filters.transformation.scaling.svg
  doc/images/filters.transformation.scaling.svg.png
  doc/images/filters.transformation.translation.svg
  doc/images/filters.transformation.translation.svg.png
  doc/stages/filters.transformation.rst
Labels: documentation

#2918 make AzP/Windows use GDAL 3
  scripts/azp/win.yml
Labels: tests

#2919 add AzP/docs build
  azure-pipelines.yml
  scripts/azp/doc.yml
Labels: documentation

#2916 Implement in_axis_ordering and out_axis_ordering for filters.reprojection
  doc/stages/filters.reprojection.rst
  filters/ReprojectionFilter.cpp
  filters/ReprojectionFilter.hpp
  pdal/SpatialReference.cpp
  pdal/SpatialReference.hpp
  pdal/private/SrsTransform.cpp
  pdal/private/SrsTransform.hpp
  test/data/las/test_epsg_4326_axis.las
  test/unit/SpatialReferenceTest.cpp
Labels: feature

#2907 PMF classification fix
  filters/PMFFilter.cpp
  filters/SMRFilter.cpp
  test/unit/filters/PMFFilterTest.cpp
Labels: bug

#2766 Add Cloth Simulation Filter (CSF)
  doc/references.rst
  doc/stages/filters.csf.rst
  doc/stages/filters.rst
  filters/CSFilter.cpp
  filters/CSFilter.hpp
  filters/private/csf/CSF.cpp
  filters/private/csf/CSF.h
  filters/private/csf/Cloth.cpp
  filters/private/csf/Cloth.h
  filters/private/csf/Constraint.cpp
  filters/private/csf/Constraint.h
  filters/private/csf/Particle.cpp
  filters/private/csf/Particle.h
  filters/private/csf/Rasterization.cpp
  filters/private/csf/Rasterization.h
  filters/private/csf/Vec3.h
  filters/private/csf/XYZReader.cpp
  filters/private/csf/XYZReader.h
  filters/private/csf/c2cdist.cpp
  filters/private/csf/c2cdist.h
  filters/private/csf/point_cloud.cpp
  filters/private/csf/point_cloud.h
  test/unit/CMakeLists.txt
  test/unit/filters/CSFilterTest.cpp
Labels: feature

#2942 Handle VLRs as pipeline arguments in writers.las
  io/LasVLR.cpp
  io/LasVLR.hpp
  io/LasWriter.cpp
  io/LasWriter.hpp
  pdal/PipelineReaderJSON.cpp
  test/data/pipeline/issue2937.json.in
  test/unit/io/LasWriterTest.cpp
Labels: bug

#2903 tiledb: add defaults for attribute filters
  doc/stages/writers.tiledb.rst
  plugins/tiledb/io/TileDBWriter.cpp
  plugins/tiledb/test/TileDBWriterTest.cpp
Labels: feature

#2944 Support range-based for loops on PointView with PointRef as reference type
  filters/HeadFilter.hpp
  filters/RandomizeFilter.hpp
  filters/SkewnessBalancingFilter.cpp
  filters/SortFilter.cpp
  filters/SortFilter.hpp
  filters/TailFilter.hpp
  pdal/PointContainer.hpp
  pdal/PointRef.hpp
  pdal/PointView.cpp
  pdal/PointView.hpp
  pdal/PointViewIter.hpp
  test/unit/PointViewTest.cpp
  test/unit/filters/SortFilterTest.cpp
  test/unit/filters/VoxelDownsizeFilterTest.cpp
  test/unit/io/EptReaderTest.cpp
Labels: developer, feature

#2947 Make file_size conditional in info call
  kernels/InfoKernel.cpp
Labels: bug

#2838 tiledb: use internal array metadata for pipeline serialization
  plugins/tiledb/CMakeLists.txt
  plugins/tiledb/io/TileDBReader.cpp
  plugins/tiledb/io/TileDBWriter.cpp
  plugins/tiledb/io/TileDBWriter.hpp
  plugins/tiledb/test/TileDBReaderTest.cpp
  plugins/tiledb/test/TileDBWriterTest.cpp
  test/data/tiledb/array/pdal.json
Labels: feature

#2948 Document filters.python feature to use equal for type
  doc/stages/filters.python.rst
Labels: documentation

#2952 TextReader::initialize(): fix memleak if parseHeader() throws exception
  io/TextReader.cpp
Labels: bug
