Repository PDAL/PDAL, pull requests merged in 2020-03, with the labels that each got.

#2860 Add normal refinement via minimum spanning tree propagation
  doc/stages/filters.normal.rst
  filters/NormalFilter.cpp
  filters/NormalFilter.hpp
  test/unit/CMakeLists.txt
  test/unit/filters/NormalFilterTest.cpp
Labels: feature

#2954 PDAL Java bindings documentation
  doc/index.rst
  doc/java.rst
Labels: documentation

#2945 ensure WKTv1 writing for LAS 1.4 #2943
  io/LasWriter.cpp
  pdal/SpatialReference.cpp
  pdal/SpatialReference.hpp
Labels: bug

#2980 Call setSpatialReference() on the table when we switch stages.
  kernels/TileKernel.cpp
Labels: bug

#2997 Cleanup for removed plugins.
  apps/pdal-config-bat.in
  apps/pdal-config.in
  cmake/modules/FindNumPy.cmake
  cmake/modules/FindSQLite3.cmake
  cmake/options.cmake
  cmake/python.cmake
  cmake/spatialite.cmake
  pdal/DbWriter.hpp
  pdal/StageExtensions.cpp
  pdal/pdal_config.cpp
  pdal/pdal_config.hpp
  pdal_features.hpp.in
Labels: bug
