Repository PDAL/PDAL, pull requests merged in 2021-04, with the labels that each got.

#3399 Fix up docker configuration issues
  scripts/docker/ubuntu/Dockerfile
  scripts/docker/ubuntu/Dockerfile.dependencies
Labels: bug

#3398 Do symmetric intersection test.
  plugins/i3s/io/Obb.cpp
  plugins/i3s/io/Obb.hpp
  plugins/i3s/test/ObbTest.cpp
Labels: bug

#3404 Fix names of dimensions received from ept.json
  io/private/ept/EptInfo.cpp
  io/private/ept/TileContents.hpp
Labels: bug

#3405 Don't write extended scan angle and regular scan angle for LASZIP
  io/LasWriter.cpp
  test/data/text/largescan.txt
  test/unit/io/LasWriterTest.cpp
Labels: bug

#3406 Allow 1.4 LAS to use geotiff for PDRF 0-5
  io/LasHeader.cpp
  io/LasHeader.hpp
Labels: feature

#3407 If there are no extended VLRs, set the offset to 0
  io/LasWriter.cpp
Labels: bug

#3408 Add zsmooth filter
  doc/stages/filters.zsmooth.rst
  filters/ZsmoothFilter.cpp
  filters/ZsmoothFilter.hpp
Labels: feature

#3413 use pkgconfig to support draco 1.4.0+ (only)
  CMakeLists.txt
  cmake/draco.cmake
  plugins/draco/CMakeLists.txt
  scripts/ci/linux/cmake.sh
  scripts/ci/linux/setup.sh
  scripts/ci/osx/cmake.sh
  scripts/ci/osx/setup.sh
  scripts/ci/win/cmake.sh
  scripts/ci/win/setup.sh
  scripts/conda/osx.sh
Labels: bug

#3417 Improve some LAS header error messages
  io/LasHeader.cpp
  io/LasHeader.hpp
  io/LasWriter.cpp
Labels: bug

#3415 Write double-precision values with more precision
  pdal/Options.hpp
  test/unit/OptionsTest.cpp
Labels: bug

#3418 Error if the specified extra bytes exceed available bytes
  io/LasReader.cpp
  io/LasUtils.cpp
  io/LasUtils.hpp
  test/unit/io/LasReaderTest.cpp
Labels: bug

#3421 Better handle fileSize() failures
  io/BpfWriter.cpp
  io/SbetReader.cpp
  pdal/util/FileUtils.cpp
  plugins/i3s/io/SlpkReader.cpp
Labels: bug

#3420 Correct description of LAS writer.
  io/LasWriter.cpp
Labels: documentation

#3419 Detect filter-only pipeline.
  kernels/PipelineKernel.cpp
  pdal/PipelineManager.cpp
  pdal/PipelineManager.hpp
  test/data/pipeline/filter-only.json.in
  test/data/pipeline/issue2937.json.in
  test/unit/apps/pcpipelineTestJSON.cpp
Labels: bug

#3416 Add where support to writers
  doc/stages/writer_opts.rst
  doc/stages/writers.draco.rst
  doc/stages/writers.raster.rst
  pdal/Filter.cpp
  pdal/Filter.hpp
  pdal/Reader.cpp
  pdal/Reader.hpp
  pdal/Stage.cpp
  pdal/Stage.hpp
  pdal/Streamable.cpp
  pdal/Writer.cpp
  pdal/Writer.hpp
  pdal/private/StageRunner.cpp
  test/unit/WhereTest.cpp
Labels: feature

#3361 Refactor Hausdorff kernel and add modified Hausdorff metric as one of the outputs
  kernels/HausdorffKernel.cpp
  pdal/PDALUtils.cpp
  pdal/PDALUtils.hpp
  test/unit/apps/HausdorffTest.cpp
Labels: feature

#3346 Add EvalKernel
  doc/apps/chamfer.rst
  doc/apps/eval.rst
  doc/apps/hausdorff.rst
  kernels/EvalKernel.cpp
  kernels/EvalKernel.hpp
Labels: feature

#3427 Eliminate some WKT round trips and use WKT2
  cmake/gdal.cmake
  filters/CropFilter.cpp
  pdal/Geometry.cpp
  pdal/private/SrsTransform.cpp
  pdal/private/SrsTransform.hpp
  pdal/private/gdal/GDALUtils.cpp
Labels: bug, policy-decision

#3426 Fix arbiter azure driver
  vendor/arbiter/arbiter.cpp
  vendor/arbiter/arbiter.hpp
Labels: bug

#3430 Make random number seeding easy
  pdal/util/CMakeLists.txt
  pdal/util/Random.cpp
  pdal/util/Random.hpp
Labels: feature

#3429 Deprecate the MrSid reader.
  doc/stages/readers.mrsid.rst
  plugins/mrsid/io/MrsidReader.cpp
Labels: policy-decision

#3432 Test support update
  pdal/util/Random.hpp
  test/unit/SpatialReferenceTest.cpp
  test/unit/Support.cpp
  test/unit/Support.hpp
  test/unit/apps/AppPluginTest.cpp
  test/unit/apps/AppTest.cpp
  test/unit/apps/pcpipelineTestJSON.cpp
Labels: tests

#3433 Support and test large file mapping
  pdal/util/FileUtils.cpp
  pdal/util/FileUtils.hpp
  test/unit/UtilsTest.cpp
Labels: bug, tests

#3442 Add nosrs option to readers.las
  doc/stages/readers.las.rst
  io/LasHeader.cpp
  io/LasHeader.hpp
  io/LasReader.cpp
Labels: performance

#3440 Remove GDAL 2.X support
  pdal/SpatialReference.cpp
  pdal/private/gdal/GDALUtils.cpp
  pdal/private/gdal/GDALUtils.hpp
Labels: policy-decision
