Repository PDAL/PDAL, pull requests merged in 2021-06, with the labels that each got.

#3466 Small typo
  doc/stages/filters.sample.rst
Labels: documentation

#3485 Catch bounds exceptions
  pdal/Metadata.cpp
Labels: bug

#3486 Initialize UUID to null
  pdal/util/Uuid.hpp
  test/unit/UuidTest.cpp
Labels: bug

#3479 support getting and setting dataset-level GDAL metadata in writers.gdal and readers.gdal
  doc/stages/writers.gdal.rst
  io/GDALReader.cpp
  io/GDALReader.hpp
  io/GDALWriter.cpp
  io/GDALWriter.hpp
  pdal/private/gdal/Raster.cpp
  pdal/private/gdal/Raster.hpp
  test/unit/io/GDALReaderTest.cpp
  test/unit/io/GDALWriterTest.cpp
Labels: feature

#3489 Don't run large file mapping test for WIN32, which doesn't support it
  test/unit/UtilsTest.cpp
Labels: tests
