Repository PDAL/PDAL, pull requests merged in 2021-09, with the labels that each got.

#3524 Don't use _USE_MATH_DEFINES locally
  cmake/win32_compiler_options.cmake
  filters/GreedyProjection.hpp
  io/OptechReader.cpp
  io/SbetReader.cpp
  io/SbetWriter.cpp
  test/unit/GeoreferenceTest.cpp
Labels: bug

#3526 Add more meaningful capability macros
  io/GeotiffSupport.cpp
  pdal/pdal_internal.hpp
Labels: bug

#3520 Improvements to filters.litree
  doc/stages/filters.litree.rst
  filters/LiTreeFilter.cpp
  filters/LiTreeFilter.hpp
Labels: documentation, bug, performance

#3515 Fix symbol export
  pdal/PointLayout.hpp
  pdal/SpatialReference.hpp
  pdal/util/Charbuf.hpp
Labels: bug

#3543 Improve pipeline document
  doc/pipeline.rst
Labels: documentation
