Repository PDAL/PDAL, pull requests merged in 2021-05, with the labels that each got.

#3425 PCD Reader issues
  io/PcdReader.cpp
Labels: bug

#3439 Forward query/headers properly during HEAD requests
  vendor/arbiter/arbiter.cpp
  vendor/arbiter/arbiter.hpp
Labels: bug

#3454 Return all points when a PointView does not have count points
  filters/FarthestPointSamplingFilter.cpp
Labels: bug

#3451 Fix teaser issue with make_unique
  plugins/teaser/filters/TeaserFilter.cpp
  plugins/teaser/filters/TeaserFilter.hpp
  plugins/teaser/filters/registration.h
Labels: bug

#3449 Set index to zero within run() s.t. we can handle multiple PointViews correctly
  filters/HeadFilter.cpp
Labels: bug

#3457 Workshop updates
  doc/workshop/conda.rst
  doc/workshop/exercises/analysis/colorization/colorization.rst
  doc/workshop/exercises/analysis/colorization/colorize.json
  doc/workshop/exercises/analysis/rasterize/classification.json
  doc/workshop/exercises/analysis/thinning/thinning.rst
  doc/workshop/exercises/info/metadata.rst
  doc/workshop/exercises/translation/entwine.json
Labels: documentation

#3455 Handle error from bounds parsing
  pdal/util/Bounds.hpp
  test/unit/BoundsTest.cpp
Labels: feature, tests
