Repository PDAL/PDAL, pull requests merged in 2022-02, with the labels that each got.

#3683 Write metadata as vlrs
  doc/stages/writers.las.rst
  io/LasWriter.cpp
  io/LasWriter.hpp
  io/private/las/Vlr.cpp
  io/private/las/Vlr.hpp
  test/unit/io/LasWriterTest.cpp
Labels: feature

#3686 Update arbiter bundle
  pdal/PDALUtils.cpp
  vendor/arbiter/arbiter.cpp
  vendor/arbiter/arbiter.hpp
Labels: bug

#3687 fix: PDALConfig.cmake install location
  cmake/config.cmake
Labels: developer
