Repository PDAL/PDAL, pull requests merged in 2022-08, with the labels that each got.

#3835 Update tile.rst
  doc/apps/tile.rst
Labels: documentation

#3842 get openscenegraph reader working again with OSG 3.6
  plugins/openscenegraph/io/OSGReader.cpp
Labels: bug

#3841 remove mrsid and fbx plugins
  doc/stages/readers.mrsid.rst
  doc/stages/readers.rst
  plugins/fbx/CMakeLists.txt
  plugins/fbx/io/FbxWriter.cpp
  plugins/fbx/io/FbxWriter.hpp
  plugins/fbx/test/FbxWriterTest.cpp
  plugins/mrsid/CMakeLists.txt
  plugins/mrsid/io/MrsidReader.cpp
  plugins/mrsid/io/MrsidReader.hpp
  plugins/mrsid/test/MrsidTest.cpp
Labels: policy-decision

#3840 Add 'binmode' to writers.gdal to support non-interpolated rasters #3215
  doc/stages/writers.gdal.rst
  io/GDALWriter.cpp
  io/GDALWriter.hpp
  io/private/GDALGrid.cpp
  io/private/GDALGrid.hpp
Labels: feature

#3845 Update Utils.cpp
  pdal/util/Utils.cpp
Labels: bug

#3837 writers.ogr: add option to populate feature attributes from dimensions
  doc/stages/writers.ogr.rst
  io/OGRWriter.cpp
  io/OGRWriter.hpp
  pdal/private/gdal/ErrorHandler.hpp
  test/data/ogr/attrs.shp.ogrinfo
  test/data/ogr/attrs_all.shp.ogrinfo
  test/data/ogr/attrs_measure.shp.ogrinfo
  test/data/ogr/creation_options.geojson.ogrinfo
  test/data/ogr/geopackage.gpkg.ogrinfo
  test/data/ogr/geopackage_attrs_all.gpkg.ogrinfo
  test/data/ogr/json.geojson.ogrinfo
  test/data/ogr/multicount.shp.ogrinfo
  test/data/ogr/multicount_2.shp.ogrinfo
  test/data/ogr/multicount_3.shp.ogrinfo
  test/data/ogr/shapefile.shp.ogrinfo
  test/data/ogr/shapefile_measure.shp.ogrinfo
  test/unit/CMakeLists.txt
  test/unit/io/OGRWriterTest.cpp
Labels: feature
