Repository PDAL/PDAL, pull requests merged in 2022-11, with the labels that each got.

#3888 CMake cleanup for plugins
  plugins/CMakeLists.txt
Labels: bug

#3893 implement #3871 and provide a windows screenWidth implementation too
  pdal/util/Utils.cpp
Labels: bug

#3896 Add missing doc about "start" option in readers.las
  doc/stages/readers.las.rst
Labels: documentation

#3898 Make writers.ogr use transactions if they are available
  io/OGRWriter.cpp
  io/OGRWriter.hpp
Labels: bug

#3897 add metadata to quickinfo and implement for readers.las
  io/LasReader.cpp
  kernels/InfoKernel.cpp
Labels: feature

#3901 update filters.hexbin.avg_pt_per_sq_unit description
  filters/HexBinFilter.cpp
Labels: documentation

#3873 Make PDAL Locale safe
  .github/workflows/linux.yml
  filters/AssignFilter.cpp
  filters/HexBinFilter.cpp
  filters/TransformationFilter.cpp
  filters/private/DimRange.cpp
  filters/private/expr/Lexer.cpp
  filters/private/hexer/HexGrid.cpp
  io/PcdHeader.cpp
  pdal/PDALUtils.cpp
  pdal/XMLSchema.cpp
  pdal/pdal_test_main.hpp
  pdal/pdal_types.hpp
  pdal/util/Bounds.cpp
  pdal/util/Bounds.hpp
  pdal/util/FileUtils.cpp
  pdal/util/Utils.cpp
  pdal/util/Utils.hpp
  pdal/util/Uuid.hpp
  plugins/tiledb/io/Bounds4D.cpp
  plugins/tiledb/io/Bounds4D.hpp
  scripts/ci/linux/test.sh
  test/unit/UtilsTest.cpp
  test/unit/apps/TileTest.cpp
  test/unit/filters/AssignFilterTest.cpp
  test/unit/filters/RangeFilterTest.cpp
  test/unit/io/GDALWriterTest.cpp
Labels: bug, feature

#3903 Cast point_count_t to into on ostream<< #3902
  io/LasWriter.cpp
  pdal/util/Utils.cpp
Labels: bug
