Repository PDAL/PDAL, pull requests merged in 2022-01, with the labels that each got.

#3657 Don't access compressor if never created
  pdal/compression/LazPerfVlrCompression.cpp
  test/unit/io/LasWriterTest.cpp
Labels: bug

#3647 Update readers.text.rst
  doc/stages/readers.text.rst
Labels: documentation

#3662 Remove PDAL_STATIC_BUILD option
  cmake/libraries.cmake
  scripts/conda/osx.sh
Labels: bug

#3665 Fix #3488, filters.csf leaving outputs in uncontrollable directories
  filters/CSFilter.cpp
  filters/CSFilter.hpp
  filters/private/csf/CSF.cpp
  filters/private/csf/CSF.h
  filters/private/csf/Cloth.cpp
  filters/private/csf/Cloth.h
Labels: bug

#3667 upgrade nhlohmann to 3.10.5.
  pdal/JsonFwd.hpp
  vendor/nlohmann/nlohmann/json.hpp
Labels: feature

#3670 support comments in pipeline json
  pdal/PipelineReaderJSON.cpp
Labels: feature

#3673 Make sure we write the correct chunk table position.
  pdal/compression/LazPerfVlrCompression.cpp
  test/unit/io/LasWriterTest.cpp
Labels: bug

#3676 Compute pointCount in CopcReader::inspect()
  io/CopcReader.cpp
  io/private/copc/Entry.cpp
  io/private/copc/Entry.hpp
Labels: feature
