Repository PDAL/PDAL, pull requests merged in 2022-04, with the labels that each got.

#3732 docs: Add what is PDAL to FAQ
  doc/faq.rst
Labels: documentation

#3744 add 'count' metadata to readers.bpf metadata output
  io/BpfReader.cpp
  test/unit/io/BpfTestBase.cpp
Labels: feature

#3747 Sort COPC output by GPSTime if available
  io/private/copcwriter/Processor.cpp
Labels: bug
