Repository PDAL/PDAL, pull requests merged in 2022-07, with the labels that each got.

#3718 Add readers.ptx
  doc/stages/readers.ptx.rst
  doc/stages/readers.rst
  io/PtxReader.cpp
  io/PtxReader.hpp
  test/data/ptx/1.2-with-color.ptx
  test/data/ptx/complex-transform.ptx
  test/data/ptx/multiple-and-transform.ptx
  test/data/ptx/no-color.ptx
  test/unit/CMakeLists.txt
  test/unit/io/PtxReaderTest.cpp
Labels: feature

#3818 fix readers.las.nosrs
  io/LasReader.cpp
  io/private/las/Header.cpp
  io/private/las/Header.hpp
Labels: bug

#3819 Support remote writing of COPC files
  io/CopcWriter.cpp
  io/CopcWriter.hpp
  pdal/PDALUtils.cpp
  pdal/PDALUtils.hpp
Labels: feature

#3821 catch up PDAL's vendored laz-perf to 3.1.0
  vendor/lazperf/detail/field_byte10.cpp
  vendor/lazperf/detail/field_byte10.hpp
  vendor/lazperf/detail/field_byte14.cpp
  vendor/lazperf/detail/field_byte14.hpp
  vendor/lazperf/detail/field_gpstime.hpp
  vendor/lazperf/detail/field_gpstime10.cpp
  vendor/lazperf/detail/field_gpstime10.hpp
  vendor/lazperf/detail/field_nir14.cpp
  vendor/lazperf/detail/field_nir14.hpp
  vendor/lazperf/detail/field_point10.cpp
  vendor/lazperf/detail/field_point10.hpp
  vendor/lazperf/detail/field_point14.cpp
  vendor/lazperf/detail/field_point14.hpp
  vendor/lazperf/detail/field_rgb10.cpp
  vendor/lazperf/detail/field_rgb10.hpp
  vendor/lazperf/detail/field_rgb14.cpp
  vendor/lazperf/detail/field_rgb14.hpp
  vendor/lazperf/detail/field_xyz.hpp
  vendor/lazperf/lazperf.hpp
  vendor/lazperf/lazperf_base.hpp
  vendor/lazperf/vlr.cpp
  vendor/lazperf/vlr.hpp
  vendor/lazperf/writers.cpp
Labels: bug

#3822 Terrasolid FBI read/write support
  doc/stages/readers.fbi.rst
  doc/stages/readers.rst
  doc/stages/writers.fbi.rst
  doc/stages/writers.rst
  io/FbiHeader.cpp
  io/FbiHeader.hpp
  io/FbiReader.cpp
  io/FbiReader.hpp
  io/FbiWriter.cpp
  io/FbiWriter.hpp
  pdal/Dimension.json
  pdal/StageExtensions.cpp
  test/data/fbi/1.2-with-color.fbi
  test/unit/CMakeLists.txt
  test/unit/io/FbiReaderTest.cpp
Labels: feature

#3824 Add wmain support to 'pdal' command for wide filename characters on Windows
  apps/CMakeLists.txt
  apps/pdal.cpp
  cmake/win32_compiler_options.cmake
  dimbuilder/CMakeLists.txt
  dimbuilder/DimBuilder.cpp
  pdal-build/ept-addon.json
  pdal/DynamicLibrary.cpp
  pdal/PDALUtils.cpp
  pdal/Reader.cpp
  pdal/util/FileUtils.cpp
  pdal/util/FileUtils.hpp
  pdal/util/IStream.hpp
  pdal/util/OStream.hpp
  test/unit/FileUtilsTest.cpp
Labels: windows, feature
