Repository PDAL/PDAL, pull requests merged in 2023-11, with the labels that each got.

#4235 Allow pdal to link with CURL target
  vendor/arbiter/CMakeLists.txt
Labels: build

#4244 implement filters.hexbin.density
  doc/stages/filters.hexbin.rst
  filters/HexBinFilter.cpp
  filters/HexBinFilter.hpp
Labels: feature

#4238 Add streaming tutorial
  doc/development/overview.rst
  doc/development/writing.rst
  examples/writing-streamer/CMakeLists.txt
  examples/writing-streamer/streamer_tutorial.cpp
  pdal/PointTable.hpp
Labels: documentation

#4236 add 'ogr' block to filters.geomdistance
  doc/stages/filters.geomdistance.rst
  filters/GeomDistanceFilter.cpp
Labels: feature

#4246 Use proper level for grid size.
  io/private/copcwriter/Grid.cpp
Labels: bug

#4233 Add and fix TileDB filter options
  plugins/tiledb/io/TileDBUtils.cpp
  plugins/tiledb/test/TileDBUtilsTest.cpp
Labels: bug

#4257 Fix convention error with `xmlErrorPtr` caused by `libxml2` API change
  pdal/XMLSchema.cpp
Labels: bug

#4259 add OWNER_WRITE permissions to installs
  CMakeLists.txt
Labels: bug
