Repository PDAL/PDAL, pull requests merged in 2023-01, with the labels that each got.

#3920 EPT and COPC fixes
  io/CopcReader.cpp
  io/EptReader.cpp
  io/EptReader.hpp
  pdal/util/ThreadPool.cpp
  pdal/util/ThreadPool.hpp
  vendor/arbiter/arbiter.cpp
Labels: bug

#3928 add filters.faceraster.edge_length option #3924
  filters/FaceRasterFilter.cpp
Labels: feature

#3926 handle CURL_VERSION_ASYNCHDNS in Arbiter
  io/StacReader.cpp
  vendor/arbiter/arbiter.cpp
Labels: bug

#3925 add filters.transformation stream test
  test/unit/filters/TransformationFilterTest.cpp
Labels: tests

#3927 Add readers.ept.ignore_unreadable
  doc/stages/readers.ept.rst
  io/EptReader.cpp
  test/data/ept/ellipsoid-nopoints/ept-build.json
  test/data/ept/ellipsoid-nopoints/ept-hierarchy/0-0-0-0.json
  test/data/ept/ellipsoid-nopoints/ept-sources/ellipsoid.json
  test/data/ept/ellipsoid-nopoints/ept-sources/manifest.json
  test/data/ept/ellipsoid-nopoints/ept.json
  test/unit/io/EptReaderTest.cpp
Labels: feature

#3930 add filters.expression to use new PDAL expression syntax
  doc/stages/filters.expression.rst
  doc/stages/filters.rst
  filters/ExpressionFilter.cpp
  filters/ExpressionFilter.hpp
  test/unit/CMakeLists.txt
  test/unit/filters/ExpressionFilterTest.cpp
Labels: feature

#3936 add copc_info to metadata output for readers.copc
  io/CopcReader.cpp
Labels: feature

#3938 Use shorter values for indices in delaunator-cpp
  filters/HagDelaunayFilter.cpp
  filters/private/delaunator.cpp
  filters/private/delaunator.hpp
Labels: feature

#3939 update laz-perf to latest 3.3.0 release
  vendor/lazperf/Extractor.hpp
  vendor/lazperf/detail/field_nir14.cpp
  vendor/lazperf/detail/field_point14.cpp
  vendor/lazperf/las.hpp
  vendor/lazperf/lazperf.cpp
  vendor/lazperf/lazperf_base.hpp
  vendor/lazperf/readers.cpp
  vendor/lazperf/vlr.hpp
  vendor/lazperf/writers.cpp
Labels: feature

#3940 address filters.overlay reprojection bug #3932
  filters/OverlayFilter.cpp
Labels: bug

#3941 Item collection
  io/StacReader.cpp
  io/StacReader.hpp
  test/data/stac/test_item_collection.json
  test/unit/io/StacReaderTest.cpp
Labels: feature

#3937 deprecate PipelineManager
  pdal/PipelineExecutor.hpp
  pdal/util/pdal_util_export.hpp
Labels: policy-decision

#3942 STAC Reader bug fixes
  io/StacReader.cpp
Labels: bug

#3950 set GDAL,PROJ,GEOTIFF env variables for our container
  scripts/docker/ubuntu/Dockerfile
Labels: bug

#3953 Fixed bounds comparisons.
  io/StacReader.cpp
  test/data/stac/test_item_collection.json
  test/unit/io/StacReaderTest.cpp
Labels: bug

#3959 Fix case where endpoint lies exactly on a grid intersection.
  filters/private/pnp/VoxelRayTrace.hpp
  test/data/filters/crop-on-edge/crop.las
  test/data/filters/crop-on-edge/pipe.json
  test/data/filters/crop-on-edge/poly.wkt
  test/data/filters/crop-on-edge/poly_pb.geojson
  test/unit/filters/CropFilterTest.cpp
Labels: bug
