Repository PDAL/PDAL, pull requests merged in 2023-08, with the labels that each got.

#4117 Add WKTv2 VLRs to COPC
  doc/stages/readers.copc.rst
  doc/stages/writers.copc.rst
  io/CopcReader.cpp
  io/CopcWriter.cpp
  io/private/copcwriter/Common.hpp
  test/unit/CMakeLists.txt
  test/unit/io/CopcWriterTest.cpp
Labels: feature

#4122 Fix OB1 error in pdal tile
  kernels/TileKernel.cpp
  test/unit/apps/TileTest.cpp
Labels: bug

#4108 straighten filter
  doc/stages/filters.rst
  doc/stages/filters.straighten.rst
  filters/StraightenFilter.cpp
  filters/StraightenFilter.hpp
  filters/private/straighten/Polyline.cpp
  filters/private/straighten/Polyline.hpp
  filters/private/straighten/Utils.cpp
  filters/private/straighten/Utils.hpp
Labels: feature

#4129 Fix copc reader leak in inspect method.
  io/CopcReader.cpp
Labels: bug

#4057 STAC Reader overhaul
  doc/stages/readers.stac.rst
  io/StacReader.cpp
  io/StacReader.hpp
  io/private/stac/Catalog.cpp
  io/private/stac/Catalog.hpp
  io/private/stac/Collection.cpp
  io/private/stac/Collection.hpp
  io/private/stac/Item.cpp
  io/private/stac/Item.hpp
  io/private/stac/ItemCollection.cpp
  io/private/stac/ItemCollection.hpp
  io/private/stac/Utils.cpp
  io/private/stac/Utils.hpp
  pdal/util/FileUtils.cpp
  test/data/stac/autzen_trim.json
  test/data/stac/local_catalog/IA_SouthCentral_1_2020.json
  test/data/stac/local_catalog/MD_GoldenBeach_2012.json
  test/data/stac/local_catalog/MI_Charlevoix_Islands_TL_2018.json
  test/data/stac/local_catalog/catalog.json
  test/data/stac/multi_type_catalog.json
  test/data/stac/test_collection.json
  test/data/stac/test_item_collection.json
  test/data/stac/test_item_collection_2.json
  test/data/stac/wrench.json
  test/data/stac/wrench.vpc
  test/unit/io/StacReaderTest.cpp
  vendor/schema-validator/json-validator.cpp
Labels: feature

#4131 add override to getName for filters.straighten
  filters/StraightenFilter.hpp
Labels: bug

#4130 revert to old-style cmake finding for PROJ due to 9.1 vs 9.2 CONFIG b…
  CMakeLists.txt
  cmake/proj.cmake
Labels: bug

#4139 Fold pdal_util into pdalcpp and no longer maintain a separate library
  CMakeLists.txt
  PDALConfig.cmake.in
  apps/CMakeLists.txt
  cmake/macros.cmake
  dimbuilder/CMakeLists.txt
  examples/CMakeLists.txt
  examples/writing-filter/CMakeLists.txt
  examples/writing-kernel/CMakeLists.txt
  examples/writing-reader/CMakeLists.txt
  examples/writing-writer/CMakeLists.txt
  pdal/util/CMakeLists.txt
  scripts/ci/win/examples.sh
Labels: policy-decision, build

#4142 remove Utils::hexDump which is not used and causes compilation securi…
  pdal/util/Utils.cpp
  pdal/util/Utils.hpp
Labels: developer

#4140 update laz-perf to 3.4.0 release - small fix for zero point files htt…
  vendor/lazperf/header.cpp
  vendor/lazperf/portable_endian.hpp
  vendor/lazperf/readers.cpp
  vendor/lazperf/writers.cpp
Labels: vendoring
