Repository PDAL/PDAL, pull requests merged in 2023-12, with the labels that each got.

#4267 Remove remaining pdal_util library references
  CMakeLists.txt
  cmake/backtrace.cmake
  cmake/execinfo.cmake
  cmake/unwind.cmake
  libpdalcpp
  pdal/util/CMakeLists.txt
  tools/lasdump/CMakeLists.txt
  tools/nitfwrap/CMakeLists.txt
Labels: bug

#4277 Update how TileDB domain is set when not provided by user
  plugins/tiledb/io/TileDBWriter.cpp
  plugins/tiledb/test/TileDBWriterTest.cpp
  plugins/tiledb/test/TileDBWriterTimeDimTest.cpp
Labels: bug

#4286 Fix getting/setting the pointFormat of LAZ-files via LasHeader
  io/LasHeader.cpp
  test/unit/io/LasReaderTest.cpp
Labels: bug

#4290 Fixed 'Edit on GitHub' link.
  doc/conf.py
Labels: documentation

#4288 Add math unary functions to AssignmentStatement in `filters.expression` and `filters.assign`
  filters/private/expr/AssignParser.cpp
  filters/private/expr/BaseParser.cpp
  filters/private/expr/BaseParser.hpp
  filters/private/expr/Expression.cpp
  filters/private/expr/Expression.hpp
  filters/private/expr/MathParser.cpp
  filters/private/expr/MathParser.hpp
  filters/private/expr/Token.hpp
  scripts/ci/environment.yml
  scripts/ci/win/setup.sh
Labels: feature

#4289 Added the height difference threshold as parameter to the CSF filter.
  doc/stages/filters.csf.rst
  filters/CSFilter.cpp
  filters/private/csf/CSF.cpp
  filters/private/csf/CSF.h
  filters/private/csf/Cloth.h
  filters/private/csf/Constraint.h
  filters/private/csf/Particle.h
  filters/private/csf/Rasterization.h
  filters/private/csf/Vec3.h
  filters/private/csf/XYZReader.h
  filters/private/csf/c2cdist.h
  filters/private/csf/point_cloud.h
Labels: feature
