Repository PDAL/PDAL, pull requests merged in 2023-02, with the labels that each got.

#3963 Documentation updates
  doc/conf.py
  doc/development/compilation/unix.rst
  doc/download.rst
  doc/requirements.txt
  doc/stages/filters.faceraster.rst
  doc/stages/filters.range.rst
  doc/stages/writers.raster.rst
Labels: documentation

#3966 Guard against bad return numbers.
  io/private/las/Summary.cpp
Labels: bug

#3967 Fix handling of string HeaderVal containing spaces
  io/CopcWriter.cpp
  io/HeaderVal.hpp
  io/LasWriter.hpp
  test/unit/io/LasWriterTest.cpp
Labels: bug

#3968 output better information when LAS Classification values can't be wri…
  io/LasWriter.cpp
Labels: bug

#3969 Miscellaneous compilation files and simplifications.
  filters/private/csf/Cloth.cpp
  io/HeaderVal.hpp
  io/private/las/Summary.cpp
  pdal/SpatialReference.cpp
Labels: bug

#3982 CI Simplification
  .github/workflows/linux.yml
  .github/workflows/osx.yml
  .github/workflows/win.yml
  plugins/draco/CMakeLists.txt
  scripts/ci/environment.yml
  scripts/ci/linux/cmake.sh
  scripts/ci/linux/setup.sh
  scripts/ci/osx/setup.sh
  scripts/ci/win/cmake.sh
  scripts/ci/win/setup.sh
  scripts/conda/win64.bat
Labels: feature

#3983 Do not hardcode -std=c++11 into pdal-config
  apps/pdal-config.in
Labels: bug

#3984 add allow_empty option to writers.gdal to write empty GDAL output
  io/GDALWriter.cpp
  io/GDALWriter.hpp
Labels: feature

#3985 reformat simple.laz to a current LASzip compressor version #3978
  test/data/apps/simple-laszip-compressor-version-1.2r0.laz
  test/data/apps/simple.laz
  test/data/laz/simple-laszip-compressor-version-1.2r0.laz
  test/data/laz/simple.laz
Labels: bug

#3992 Streaming support for readers.tindex
  io/TIndexReader.cpp
  io/TIndexReader.hpp
  scripts/ci/osx/setup.sh
Labels: bug, feature

#3989 Streamable readers.stac
  io/StacReader.cpp
  io/StacReader.hpp
  test/unit/io/StacReaderTest.cpp
Labels: bug
