Repository PDAL/PDAL, pull requests merged in 2023-09, with the labels that each got.

#4158 PCD reading of 64bit values does not work
  io/PcdReader.cpp
  scripts/ci/linux/setup.sh
  test/data/pcd/autzen-utm.pcd
  test/unit/io/PcdReaderTest.cpp
Labels: bug

#4155 Add tolerance in barycentric interpolation
  pdal/private/MathUtils.cpp
  pdal/private/MathUtils.hpp
  test/data/filters/faceraster_numerical_imprecision.laz
  test/unit/filters/FaceRasterTest.cpp
Labels: bug

#4154 Enhancements/fixes related to coordinate epochs
  pdal/SpatialReference.cpp
  pdal/SpatialReference.hpp
  pdal/private/SrsTransform.cpp
Labels: feature

#4177 Standalone plugin builds
  cmake/standalone.cmake
  plugins/draco/CMakeLists.txt
  plugins/draco/build/build.ninja
  plugins/e57/CMakeLists.txt
  plugins/hdf/CMakeLists.txt
  plugins/icebridge/CMakeLists.txt
  plugins/nitf/CMakeLists.txt
  plugins/openscenegraph/CMakeLists.txt
  plugins/pgpointcloud/CMakeLists.txt
  plugins/rdb/CMakeLists.txt
  plugins/rxp/CMakeLists.txt
  plugins/teaser/CMakeLists.txt
  plugins/tiledb/CMakeLists.txt
  plugins/trajectory/CMakeLists.txt
  scripts/conda/standalone.bat
  vendor/utfcpp/CMakeLists.txt
Labels: build

#4181 fix crashing for non-sql OGR filters
  pdal/private/gdal/GDALUtils.cpp
Labels: bug

#4184 Terminate when input is smaller than requested output size or radius has grown too small
  filters/RelaxationDartThrowing.cpp
  filters/RelaxationDartThrowing.hpp
  test/unit/CMakeLists.txt
  test/unit/filters/RelaxationDartThrowingTest.cpp
Labels: bug

#4183 COPC/LAS: legacy return counts for LAS1.4/PDRF>=6
  io/LasReader.cpp
  io/LasReader.hpp
  io/private/copcwriter/Output.cpp
  io/private/las/Header.cpp
  test/unit/io/LasWriterTest.cpp
Labels: bug

#4189 add UserData as a synonym for user_data for both Stage and Dimension …
  pdal/Dimension.json
  pdal/Options.hpp
  pdal/Stage.cpp
Labels: feature

#4187 Test fixes
  pdal/util/Bounds.cpp
  test/unit/BoundsTest.cpp
  test/unit/filters/StatsFilterTest.cpp
  test/unit/io/CopcWriterTest.cpp
Labels: tests, bug

#4190 do not concatinate lists into comma-separated strings in Options::toM…
  pdal/Options.hpp
Labels: policy-decision

#4198 Improve detection of libunwind on macOS
  cmake/modules/FindLibunwind.cmake
Labels: build

#4197 Await EPT reader's thread-pool in done()
  io/EptReader.cpp
Labels: bug
