Repository PDAL/PDAL, pull requests merged in 2023-05, with the labels that each got.

#4040 Allows mixing user set and auto-generate domains for the TileDB writer
  plugins/tiledb/io/TileDBWriter.cpp
  plugins/tiledb/io/TileDBWriter.hpp
Labels: feature

#4044 Fix MinGW builds
  io/OptechReader.cpp
Labels: build

#4043 Don't use const_cast
  pdal/Geometry.cpp
Labels: bug

#4046 implement geojson and object pdal::Bounds parsing #4042
  pdal/SrsBounds.cpp
  pdal/util/Bounds.cpp
  pdal/util/Bounds.hpp
  pdal/util/CMakeLists.txt
  test/unit/BoundsTest.cpp
Labels: feature

#4060 support standalone builds for rxp
  plugins/rxp/CMakeLists.txt
Labels: build

#4058 Point view sorting stopgap
  filters/SkewnessBalancingFilter.cpp
  filters/SortFilter.cpp
  io/private/copcwriter/Processor.cpp
  pdal/PointRef.hpp
  pdal/PointView.hpp
  scripts/ci/osx/setup.sh
  test/unit/filters/SortFilterTest.cpp
  test/unit/io/CopcReaderTest.cpp
  test/unit/io/EptReaderTest.cpp
Labels: bug
