Repository PDAL/PDAL, pull requests merged in 2023-07, with the labels that each got.

#4098 Readers.tindex.reader args
  doc/stages/readers.tindex.rst
  io/TIndexReader.cpp
  io/TIndexReader.hpp
Labels: feature

#4012 readers.gdal improvements
  filters/ColorizationFilter.cpp
  filters/DEMFilter.cpp
  filters/HagDemFilter.cpp
  io/GDALReader.cpp
  io/GDALReader.hpp
  io/LasWriter.cpp
  pdal/private/gdal/Raster.cpp
  pdal/private/gdal/Raster.hpp
Labels: feature

#4103 implement STANDALONE plugin building for common plugins
  .github/workflows/linux.yml
  CMakeLists.txt
  cmake/libraries.cmake
  cmake/standalone.cmake
  plugins/cpd/CMakeLists.txt
  plugins/draco/CMakeLists.txt
  plugins/e57/CMakeLists.txt
  plugins/hdf/CMakeLists.txt
  plugins/i3s/CMakeLists.txt
  plugins/icebridge/CMakeLists.txt
  plugins/mbio/CMakeLists.txt
  plugins/nitf/CMakeLists.txt
  plugins/openscenegraph/CMakeLists.txt
  plugins/pgpointcloud/CMakeLists.txt
  plugins/rdb/CMakeLists.txt
  plugins/rxp/CMakeLists.txt
  plugins/teaser/CMakeLists.txt
  plugins/tiledb/CMakeLists.txt
  plugins/trajectory/CMakeLists.txt
  scripts/ci/environment.yml
  scripts/ci/linux/standalone.sh
Labels: build

#4052 Implement Gnuinstalldirs support
  .github/workflows/linux.yml
  CMakeLists.txt
  cmake/common.cmake
  cmake/install_dirs.cmake
  cmake/macros.cmake
  examples/CMakeLists.txt
  scripts/ci/linux/examples.sh
  scripts/ci/osx/examples.sh
Labels: feature, build

#4113 Warnings cleanup
  filters/GreedyProjection.cpp
  io/TIndexReader.cpp
  scripts/conda/osx.sh
Labels: developer

#4118 Add dependabot.yml for checking gh-actions
  .github/dependabot.yml
Labels: developer
