Repository PDAL/PDAL, pull requests merged in 2024-06, with the labels that each got.

#4417 Changes for Matlab plugin to compile under macOS.
  cmake/matlab.cmake
  cmake/modules/FindMatlab.cmake
  plugins/matlab/CMakeLists.txt
Labels: build

#4419 Fix doc message in crop filter
  filters/CropFilter.cpp
Labels: documentation

#4421 E57 plugins need to link against PDAL when building standalone
  plugins/e57/CMakeLists.txt
  scripts/ci/win/cmake.sh
Labels: build

#4428 implement 'auto' as default CRS for BPF writer #4418
  io/BpfWriter.cpp
  io/BpfWriter.hpp
Labels: feature
