Repository PDAL/PDAL, pull requests merged in 2024-12, with the labels that each got.

#4561 `filters.expression` support for filtering NaN and LOWEST/HIGHEST
  filters/ExpressionFilter.cpp
  filters/private/expr/AssignParser.cpp
  filters/private/expr/ConditionalExpression.hpp
  filters/private/expr/ConditionalParser.cpp
  filters/private/expr/ConditionalParser.hpp
  filters/private/expr/Expression.cpp
  filters/private/expr/Expression.hpp
  filters/private/expr/MathParser.cpp
  filters/private/expr/MathParser.hpp
  io/FauxReader.cpp
  io/FauxReader.hpp
  test/unit/filters/AssignFilterTest.cpp
  test/unit/filters/ExpressionFilterTest.cpp
  test/unit/filters/GridDecimationFilterTest.cpp
  test/unit/io/LasWriterTest.cpp
Labels: feature

#4575 Use tabs for the OS variants of using Conda
  doc/workshop/conda.md
Labels: documentation

#4580 Adapt GDAL's backport bot
  .github/workflows/backport.yml
Labels: developer, github_actions, backport 2.8-maintenance

#4579 Isolate dependencies and tasks for doc generation and preview
  doc/development/documentation-quickstart.md
  pixi.lock
  pixi.toml
Labels: backport 2.8-maintenance

#4584 `writers.pcd` binary mode fixes
  io/PcdWriter.cpp
  io/PcdWriter.hpp
Labels: bug, backport 2.8-maintenance

#4583 Fix where_merge == true when no views are returned.
  doc/stages/filter_opts.md
  doc/stages/writer_opts.md
  pdal/private/StageRunner.cpp
  test/unit/WhereTest.cpp
Labels: backport 2.8-maintenance

#4587 update community page with link to Matrix
  doc/community.md
Labels: documentation, backport 2.8-maintenance

#4590 Fix #4578, doc nit in readers.rdb
  doc/stages/readers.rdb.md
Labels: documentation, backport 2.8-maintenance

#4568 Enhance `filters.gpstimeconvert` to make it streamable
  doc/stages/filters.gpstimeconvert.md
  filters/GpsTimeConvert.cpp
  filters/GpsTimeConvert.hpp
Labels: performance

#4596 adapt standard gitignore for CMake files
  .gitignore
Labels: build, backport 2.8-maintenance

#4592 Local documentation build conveniences
  doc/Makefile
  doc/README.md
  doc/_config.yml
  doc/_static/logo/hobu-emblem-32x32.png
  doc/conf.py
  doc/environment.yml
  doc/local-build-environment.yml
  doc/pdal_rtd/README.md
  doc/pdal_rtd/breadcrumbs.html
  doc/pdal_rtd/footer.html
  doc/pdal_rtd/searchbox.html
  doc/pdal_rtd/static/css/pdal.css
  doc/pdal_rtd/static/fonts/miriamlibre-bold-webfont.eot
  doc/pdal_rtd/static/fonts/miriamlibre-bold-webfont.svg
  doc/pdal_rtd/static/fonts/miriamlibre-bold-webfont.ttf
  doc/pdal_rtd/static/fonts/miriamlibre-bold-webfont.woff
  doc/pdal_rtd/static/fonts/miriamlibre-bold-webfont.woff2
  doc/pdal_rtd/static/fonts/miriamlibre-regular-webfont.eot
  doc/pdal_rtd/static/fonts/miriamlibre-regular-webfont.svg
  doc/pdal_rtd/static/fonts/miriamlibre-regular-webfont.ttf
  doc/pdal_rtd/static/fonts/miriamlibre-regular-webfont.woff
  doc/pdal_rtd/static/fonts/miriamlibre-regular-webfont.woff2
  doc/pdal_rtd/static/fonts/proximanova-light-webfont.eot
  doc/pdal_rtd/static/fonts/proximanova-light-webfont.otf
  doc/pdal_rtd/static/fonts/proximanova-light-webfont.svg
  doc/pdal_rtd/static/fonts/proximanova-light-webfont.ttf
  doc/pdal_rtd/static/fonts/proximanova-light-webfont.woff
  doc/pdal_rtd/static/fonts/proximanova-sbold-webfont.eot
  doc/pdal_rtd/static/fonts/proximanova-sbold-webfont.otf
  doc/pdal_rtd/static/fonts/proximanova-sbold-webfont.svg
  doc/pdal_rtd/static/fonts/proximanova-sbold-webfont.ttf
  doc/pdal_rtd/static/fonts/proximanova-sbold-webfont.woff
  doc/pdal_rtd/static/fonts/sintony-bold-webfont.eot
  doc/pdal_rtd/static/fonts/sintony-bold-webfont.svg
  doc/pdal_rtd/static/fonts/sintony-bold-webfont.ttf
  doc/pdal_rtd/static/fonts/sintony-bold-webfont.woff
  doc/pdal_rtd/static/fonts/sintony-bold-webfont.woff2
  doc/pdal_rtd/static/fonts/sintony-regular-webfont.eot
  doc/pdal_rtd/static/fonts/sintony-regular-webfont.svg
  doc/pdal_rtd/static/fonts/sintony-regular-webfont.ttf
  doc/pdal_rtd/static/fonts/sintony-regular-webfont.woff
  doc/pdal_rtd/static/fonts/sintony-regular-webfont.woff2
  doc/pdal_rtd/static/fonts/sourcecodepro-regular-webfont.eot
  doc/pdal_rtd/static/fonts/sourcecodepro-regular-webfont.svg
  doc/pdal_rtd/static/fonts/sourcecodepro-regular-webfont.ttf
  doc/pdal_rtd/static/fonts/sourcecodepro-regular-webfont.woff
  doc/pdal_rtd/theme.conf
  doc/pdal_rtd/versions.html
  doc/tutorial/las.md
Labels: documentation, backport 2.8-maintenance

#4573 New argument to process OGR JSON blocks
  doc/stages/filters.crop.md
  doc/stages/ogr_json.md
  doc/stages/readers.copc.md
  doc/stages/readers.ept.md
  doc/stages/readers.tindex.md
  filters/CropFilter.cpp
  filters/GeomDistanceFilter.cpp
  io/CopcReader.cpp
  io/EptReader.cpp
  io/TIndexReader.cpp
  pdal/private/OGRSpec.cpp
  pdal/private/OGRSpec.hpp
  pdal/private/gdal/GDALUtils.cpp
  pdal/private/gdal/GDALUtils.hpp
  test/unit/CMakeLists.txt
  test/unit/OGRSpecTest.cpp
  test/unit/filters/CropFilterTest.cpp
  test/unit/io/CopcReaderTest.cpp
  test/unit/io/EptReaderTest.cpp
Labels: feature
