Repository PDAL/PDAL, pull requests merged in 2024-08, with the labels that each got.

#4471 Don't copy PointView pointers to temporaries.
  pdal/PointRef.cpp
  pdal/PointRef.hpp
Labels: bug

#4474 Make DbWriters not need a filename.
  pdal/DbWriter.hpp
Labels: bug

#4477 add 'bins' item to filters.stats output
  filters/StatsFilter.cpp
Labels: feature

#4478 Optional stable sort for filters.sort
  filters/SortFilter.cpp
  filters/SortFilter.hpp
  pdal/PointRef.cpp
  pdal/PointRef.hpp
  test/unit/filters/SortFilterTest.cpp
Labels: bug, feature

#4469 Implement ``filters.label_duplicates``
  doc/stages/filters.label_duplicates.rst
  doc/stages/filters.rst
  filters/LabelDuplicatesFilter.cpp
  filters/LabelDuplicatesFilter.hpp
  pdal/Dimension.json
  test/data/text/duplicates-sorted.txt
  test/data/text/duplicates-unsorted.txt
  test/unit/CMakeLists.txt
  test/unit/filters/LabelDuplicatesFilterTest.cpp
Labels: feature, stage

#4482 Default writers.las to LAS 1.4
  io/LasWriter.cpp
  test/unit/io/LasWriterTest.cpp
Labels: policy-decision

#4483 Prepare assignment statement before checking dimension existence.
  filters/AssignFilter.cpp
  test/unit/filters/AssignFilterTest.cpp
Labels: bug

#4485 Default writers.las.dataformat_id to 7
  io/LasWriter.cpp
  scripts/conda/osx.sh
  test/unit/apps/RandomTest.cpp
  test/unit/io/LasWriterTest.cpp
Labels: policy-decision

#4487 Add `filters.expressionstats` and `pdal info --breakout` option
  doc/stages/filters.expressionstats.rst
  doc/stages/filters.rst
  filters/ExpressionStatsFilter.cpp
  filters/ExpressionStatsFilter.hpp
  kernels/InfoKernel.cpp
  kernels/InfoKernel.hpp
Labels: feature

#4468 Support sorting multiple dimensions at once in `filters.sort`
  doc/stages/filters.sort.rst
  filters/LabelDuplicatesFilter.cpp
  filters/SortFilter.cpp
  filters/SortFilter.hpp
  test/unit/filters/LabelDuplicatesFilterTest.cpp
Labels: feature
