Repository PDAL/PDAL, pull requests merged in 2024-03, with the labels that each got.

#4348 filters.decimation: support non-integer step
  doc/stages/filters.decimation.rst
  filters/DecimationFilter.cpp
  filters/DecimationFilter.hpp
  test/unit/filters/DecimationFilterTest.cpp
Labels: feature

#4349 rearrange writers.arrow a little bit for better performance
  doc/stages/writers.arrow.rst
  plugins/arrow/io/ArrowCommon.hpp
  plugins/arrow/io/ArrowWriter.cpp
  plugins/arrow/io/ArrowWriter.hpp
Labels: performance

#4360 provide a better warning for classifications being written into PDRFs…
  io/LasWriter.cpp
Labels: documentation

#4359 Control readers.ept thread queue more carefully to prevent it from filling too fast
  io/EptReader.cpp
Labels: bug

#4363 Don't do LAS ready processing if there are no points.
  io/LasReader.cpp
Labels: bug

#4369 use CONFIG for Draco and Arrow. Relax Draco to 1.5+
  cmake/arrow.cmake
  plugins/draco/CMakeLists.txt
Labels: build

#4365 we do not need to bring in GDAL for the Arrow plugins
  plugins/arrow/CMakeLists.txt
Labels: bug
