Repository PDAL/PDAL, pull requests merged in 2024-11, with the labels that each got.

#4549 Don't forward VLRs unless requested.
  io/CopcWriter.cpp
  io/LasVLR.hpp
Labels: bug

#4531 Tile Index creation: add multithreaded support, where query support, new options
  doc/apps/tindex.md
  kernels/TIndexKernel.cpp
  kernels/TIndexKernel.hpp
  pdal/PipelineManager.cpp
  pdal/PipelineManager.hpp
  test/unit/CMakeLists.txt
  test/unit/apps/TIndexTest.cpp
Labels: feature

#4556 PROJ style RTD config
  .github/workflows/auto_tag_stable.yml
  HOWTORELEASE.txt
Labels: documentation

#4553 document that filters.poisson doesnt scale colors #4493
  doc/stages/filters.poisson.md
Labels: documentation
