Repository PDAL/PDAL, pull requests merged in 2024-02, with the labels that each got.

#4314 Use correct location for bash completion files
  CMakeLists.txt
Labels: bug

#4307 Added threading functionality to filters.overlay
  doc/stages/filters.overlay.rst
  filters/OverlayFilter.cpp
  filters/OverlayFilter.hpp
  pdal/Polygon.cpp
  pdal/Polygon.hpp
Labels: feature

#4329 doc fixes from #4270
  .github/workflows/codeql.yml
  doc/tutorial/ground-filters-pipeline.json
Labels: documentation

#4330 Initial commit of Sparse Surface filter
  doc/stages/filters.rst
  doc/stages/filters.sparsesurface.rst
  filters/SparseSurfaceFilter.cpp
  filters/SparseSurfaceFilter.hpp
Labels: feature
