Repository PDAL/PDAL, pull requests merged in 2024-01, with the labels that each got.

#4291 Use standard CMake installation locations
  CMakeLists.txt
  cmake/macros.cmake
  plugins/icebridge/CMakeLists.txt
  scripts/ci/linux/examples.sh
  scripts/conda/osx.sh
Labels: build

#4309 Add extra dim support to writers.copc.
  doc/stages/writers.copc.rst
  io/CopcWriter.cpp
  io/LasWriter.cpp
  io/private/copcwriter/Common.hpp
  io/private/las/Utils.cpp
  io/private/las/Utils.hpp
  test/unit/io/CopcWriterTest.cpp
Labels: feature

#4311 [Doc] Update writers documentation about LAZ support
  doc/stages/writers.rst
Labels: documentation
