Repository PDAL/PDAL, pull requests merged in 2025-01, with the labels that each got.

#4603 Handle relative paths to STAC assets correctly
  io/private/stac/Utils.cpp
Labels: bug, backport 2.8-maintenance

#4610 add zenodo citation information
  CITATION.cff
  HOWTORELEASE.md
Labels: documentation, backport 2.8-maintenance

#4608 Use gdal_fwd.hpp when available for forward declarations
  CMakeLists.txt
  pdal/Geometry.hpp
  pdal/private/gdal/GDALUtils.hpp
  pdal/private/gdal/SpatialRef.hpp
Labels: bug, backport 2.8-maintenance

#4613 [Backport 2.8-maintenance] Add new section to pipeline docs: "multiple writers and output types"
  doc/pipeline.md
Labels: documentation

#4615 Source tree cleanups
  AUTHORS.txt
  CITATION
  CITATION.cff
  CONTRIBUTING.md
  LICENSE.txt
  README.md
  RELEASENOTES.txt
  apps/CMakeLists.txt
  doc/_config.yml
  doc/references.md
  plugins/arrow/CMakeLists.txt
  tools/lasdump/CMakeLists.txt
  vendor/gtest/CMakeLists.txt
Labels: backport 2.8-maintenance

#4620 Define destructor in source file for CSFilter.
  filters/CSFilter.cpp
  filters/CSFilter.hpp
Labels: bug, backport 2.8-maintenance

#4624 upload .conda files from conda package build CI
  .github/workflows/conda.yml
  scripts/ci/conda/compile.sh
  scripts/ci/conda/upload.sh
Labels: github_actions, backport 2.8-maintenance

#4631 Issue 4630
  filters/PoissonFilter.cpp
  vendor/kazhdan/PoissonRecon.h
Labels: backport 2.8-maintenance

#4634 Update include directives for LasReader and LasHeader in transition from libLAS to PDAL guide
  doc/api/transition/index.md
Labels: backport 2.8-maintenance
