Repository PDAL/PDAL, pull requests merged in 2025-05, with the labels that each got.

#4703 Add check for unsupported field lengths in `tindex create`
  kernels/TIndexKernel.cpp
  kernels/TIndexKernel.hpp
  test/unit/apps/TIndexTest.cpp
Labels: bug

#4695 Update vendored delaunator for `filters.hag_delaunay`
  filters/HagDelaunayFilter.cpp
  filters/private/delaunator.cpp
  filters/private/delaunator.hpp
Labels: bug

#4705 Stop including <sys/timeb.h> unless on WIN32
  vendor/kazhdan/MyTime.h
Labels: build

#4708 switch GDALWriterTest to ENVI driver
  cmake/win32_compiler_options.cmake
  scripts/ci/current-environment.yml
  test/unit/io/GDALWriterTest.cpp
Labels: tests

#4716 move `readers.copc` thread pool init to initialize
  io/CopcReader.cpp
  test/unit/io/CopcReaderTest.cpp
Labels: bug

#4714 Add an example of using VSI
  doc/VSI.md
  doc/stages/readers.md
Labels: documentation

#4717 Update entwine.md
  doc/workshop/introduction/entwine.md
Labels: documentation
