Repository PDAL/PDAL, pull requests merged in 2025-04, with the labels that each got.

#4653 Add `writers.spz` and `readers.spz` (open 3DGS format from Niantic)
  CMakeLists.txt
  doc/_toc.yml
  doc/stages/readers.spz.md
  doc/stages/writers.spz.md
  io/SpzReader.cpp
  io/SpzReader.hpp
  io/SpzWriter.cpp
  io/SpzWriter.hpp
  test/data/spz/fourth_st.spz
  test/unit/CMakeLists.txt
  test/unit/io/SpzReaderTest.cpp
  test/unit/io/SpzWriterTest.cpp
  vendor/spz/CMakeLists.txt
  vendor/spz/LICENSE
  vendor/spz/README.md
  vendor/spz/src/cc/load-spz.cc
  vendor/spz/src/cc/load-spz.h
  vendor/spz/src/cc/splat-c-types.cc
  vendor/spz/src/cc/splat-c-types.h
  vendor/spz/src/cc/splat-types.cc
  vendor/spz/src/cc/splat-types.h
Labels: feature

#4668 Geometry.hpp: fix compatibility with GDAL master in debug mode
  pdal/Geometry.hpp
Labels: bug, backport 2.8-maintenance

#4666 Use modern CMake targets for required libraries
  CMakeLists.txt
  cmake/geotiff.cmake
  cmake/lzma.cmake
  cmake/zlib.cmake
  cmake/zstd.cmake
  scripts/conda/osx.sh
Labels: build

#4675 Fix READTHEDOCS_CANONICAL_URL
  .readthedocs.yaml
Labels: documentation, backport 2.8-maintenance

#4680 guard pragma usages only relevant to msvc
  io/Ilvis2MetadataReader.cpp
  io/private/copc/Tile.cpp
  io/private/las/Header.hpp
  pdal/Geometry.cpp
  pdal/compression/LazPerfVlrCompression.cpp
  pdal/pdal_export.hpp
  pdal/private/gdal/GDALUtils.cpp
  pdal/private/gdal/Raster.cpp
  pdal/util/Charbuf.hpp
  pdal/util/ProgramArgs.hpp
  scripts/ci/linux/examples.sh
Labels: build

#4681 floor values before cast when creating grid in `filters.voxelcentroidnearestneighbor`
  filters/VoxelCentroidNearestNeighborFilter.cpp
  pdal/PointView.hpp
  test/unit/CMakeLists.txt
  test/unit/filters/VoxelCenterNearestNeighborFilterTest.cpp
  test/unit/filters/VoxelCentroidNearestNeighborFilterTest.cpp
Labels: bug, backport 2.8-maintenance

#4687 Clean up some annoying warnings
  filters/private/hexer/BaseGrid.cpp
  scripts/ci/linux/cmake.sh
  scripts/ci/win/cmake.sh
  test/unit/LzmaTest.cpp
  vendor/h3/include/polyfill.h
Labels: build

#4684 enable remote capability to `readers.sbet`
  doc/stages/readers.sbet.md
  io/SbetReader.cpp
  io/SbetReader.hpp
Labels: feature

#4688 `filters.hexbin`: allow sampling with small point counts
  filters/HexBinFilter.cpp
  filters/private/hexer/BaseGrid.cpp
  filters/private/hexer/BaseGrid.hpp
  test/unit/filters/HexbinFilterTest.cpp
Labels: bug

#4689 Implement `filters.divider.expression` to break on expression
  doc/stages/filters.divider.md
  filters/DividerFilter.cpp
  filters/DividerFilter.hpp
  test/unit/filters/DividerFilterTest.cpp
Labels: feature

#4699 Fix `readers.stac` testing segfaults
  io/StacReader.cpp
  io/private/stac/Catalog.cpp
  io/private/stac/Item.cpp
  io/private/stac/Item.hpp
  io/private/stac/ItemCollection.cpp
  io/private/stac/ItemCollection.hpp
Labels: bug, backport 2.8-maintenance

#4697 Fix build with GDAL 3.11.0 debug (`GDAL_DEBUG`)
  filters/OverlayFilter.cpp
  filters/OverlayFilter.hpp
  io/TIndexReader.cpp
  io/TIndexReader.hpp
  kernels/TIndexKernel.cpp
  kernels/TIndexKernel.hpp
  kernels/private/density/OGR.hpp
  pdal/Geometry.cpp
  pdal/SpatialReference.cpp
  pdal/private/gdal/GDALUtils.cpp
  pdal/private/gdal/SpatialRef.cpp
  pdal/private/gdal/SpatialRef.hpp
Labels: bug, backport 2.8-maintenance
