Repository PDAL/PDAL, pull requests merged in 2025-02, with the labels that each got.

#4640 [Backport 2.8-maintenance] Fix bad calculation for max width cases in `readers.copc`
  io/private/copc/Key.hpp
Labels: bug

#4611 Update Arrow Writer. Handle unsupported fields in reader.
  cmake/options.cmake
  pdal/DimUtil.hpp
  plugins/arrow/CMakeLists.txt
  plugins/arrow/io/ArrowCommon.hpp
  plugins/arrow/io/ArrowReader.cpp
  plugins/arrow/io/ArrowReader.hpp
  plugins/arrow/io/ArrowWriter.cpp
  plugins/arrow/io/ArrowWriter.hpp
  plugins/arrow/test/ArrowReaderTest.cpp
  plugins/arrow/test/ArrowWriterTest.cpp
Labels: backport 2.8-maintenance

#4641 Read quickinfo or filters.stats to create TileDB array
  plugins/tiledb/io/TileDBWriter.cpp
  plugins/tiledb/test/TileDBWriterTest.cpp
Labels: backport 2.8-maintenance

#4593 Add glob functionality for local and remote files
  kernels/TIndexKernel.cpp
  kernels/TileKernel.cpp
  pdal/PDALUtils.cpp
  pdal/PDALUtils.hpp
  pdal/PipelineReaderJSON.cpp
Labels: feature

#4577 Handle multiple extrabyte VLR definitions in `readers.las` and `readers.copc`
  doc/stages/readers.las.md
  io/LasReader.cpp
  io/LasReader.hpp
  io/private/las/Utils.hpp
  test/data/laz/las_with_several_extra_byte_bloc.laz
  test/unit/io/LasReaderTest.cpp
Labels: feature

#4656 tell user we are downloading a lot of points in readers.copc
  io/CopcReader.cpp
Labels: bug, backport 2.8-maintenance
